# BUUCTF 2018 Online Tool

version: "2"

services:

  web:
    build: .
    image: ctfz/buuctf_2018_online_tool
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{this_is_flag}
