version: "2"

services:

  web:
    build: .
    image: ctfz/ciscn_2019_web_northern_china_day1_web2
    restart: always
    ports:
      - "127.0.0.1:8083:5000"
    environment:
      - FLAG=flag{this_is_flag}
