# Generated by Django 3.2.16 on 2023-02-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0006_auto_20230210_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
