# Generated by Django 3.2.16 on 2023-02-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0009_auto_20230210_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('declaration', models.CharField(blank=True, max_length=32, verbose_name='宣言')),
                ('describe', models.CharField(blank=True, max_length=256, verbose_name='简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('captain', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamCaptain', to=settings.AUTH_USER_MODEL, verbose_name='队长')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='CTFz.team', verbose_name='团队'),
        ),
    ]
