# Generated by Django 3.2.16 on 2023-02-10 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0011_auto_20230210_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签列表',
                'verbose_name_plural': '标签列表',
                'db_table': 'tag',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='describe',
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='题目名称')),
                ('environment_type', models.CharField(choices=[('dynamic', '动态'), ('static', '静态')], default='dynamic', max_length=7, verbose_name='环境类型')),
                ('describe', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('score', models.PositiveIntegerField(default=1, verbose_name='分值')),
                ('state', models.BooleanField(choices=[(True, '开放'), (False, '隐藏')], default=True, verbose_name='状态')),
                ('fixed_flag', models.CharField(blank=True, help_text='若为静态环境请设置此项', max_length=128, verbose_name='固定的flag值')),
                ('attachment', models.FileField(blank=True, help_text='若有附件请设置此项', upload_to='attachment')),
                ('difficulty', models.FloatField(default=1.0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='难度')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTFz.category', verbose_name='题目分类')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'challenge',
            },
        ),
    ]
