# Generated by Django 3.2.16 on 2023-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0012_auto_20230210_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='declaration',
            new_name='declare',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='attachment',
            field=models.FileField(blank=True, help_text='若有附件请设置此项', upload_to='attachment', verbose_name='附件'),
        ),
    ]
