# Generated by Django 3.2.16 on 2023-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0013_auto_20230210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tag',
            field=models.ManyToManyField(blank=True, to='CTFz.Tag', verbose_name='标签'),
        ),
    ]
