# Generated by Django 3.2.16 on 2023-02-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0015_auto_20230210_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='solve_user',
            new_name='solve_info',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='solve_challenge',
            new_name='solve_info',
        ),
    ]
