# Generated by Django 3.2.16 on 2023-02-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0016_auto_20230210_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solveinfo',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTFz.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='solveinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
