# Generated by Django 3.2.16 on 2023-02-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTFz', '0018_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('state', models.BooleanField(default=False, verbose_name='操作状态')),
                ('team', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CTFz.team', verbose_name='团队')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
                'db_table': 'join_request',
            },
        ),
    ]
