# hitcon 2016 Leaking
version: "2"

services:

  web:
    build: .
    image: ctfz/hitcon_2016_leaking
    restart: always
    environment:
      - FLAG=flag{this_is_flag}
    ports:
      - "127.0.0.1:8300:3000"
