# QWB 2019 SuperSqli

version: "2"

services:

  web:
    build: .
    image: ctfz/qwb_2019_supersqli
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{this_is_flag}
