version: "2"

services:

  web:
    build: .
    image: ctfz/ciscn_2019_web_northern_china_day2_web1
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{this_is_flag}
