# Generated by Django 3.2.16 on 2022-11-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='分值')),
                ('mark_total', models.PositiveIntegerField(default=0, verbose_name='总评分')),
                ('mark_count', models.PositiveIntegerField(default=0, verbose_name='评分人数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='challenge_file/', verbose_name='文件路径')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='challenge.challenge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'challenge_file',
            },
        ),
    ]
