# Generated by Django 3.2.16 on 2022-11-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='value',
        ),
    ]
