# Generated by Django 3.2.16 on 2022-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='type',
        ),
        migrations.AddField(
            model_name='challenge',
            name='environment_type',
            field=models.CharField(choices=[('docker', 'docker'), ('文件', 'file')], default='docker', max_length=20, verbose_name='环境类型'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='describe',
            field=models.CharField(default='', max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='score',
            field=models.PositiveIntegerField(default=1, verbose_name='分值'),
        ),
    ]
