# Generated by Django 3.2.16 on 2022-11-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=2, max_length=64, verbose_name='分类名'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='category',
            table='challenge_category',
        ),
    ]
