# Generated by Django 3.2.16 on 2023-01-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='mark_count',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='mark_total',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.SmallIntegerField(default=1, verbose_name='难度'),
        ),
    ]
