# Generated by Django 3.2.16 on 2022-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDockerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='镜像名')),
                ('port', models.PositiveIntegerField(default=80, verbose_name='内部端口')),
                ('memory_limit', models.PositiveSmallIntegerField(default=128, verbose_name='内存限制')),
                ('cpu_limit', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='CPU限制')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'challenge_docker_config',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='describe',
            field=models.CharField(default='', max_length=128, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default='', max_length=128, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_fixed_flag',
            field=models.BooleanField(default=False, verbose_name='flag是否固定'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='state',
            field=models.BooleanField(choices=[(True, '开放'), (False, '隐藏')], default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('docker', 'docker'), ('附件', '附件')], default='docker', max_length=20, verbose_name='类型'),
        ),
    ]
