# Generated by Django 3.2.16 on 2022-11-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20221124_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengedockerconfig',
            options={'verbose_name': 'docker设置', 'verbose_name_plural': 'docker设置'},
        ),
    ]
