# Generated by Django 3.2.16 on 2022-11-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20221124_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.category', verbose_name='题目分类'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='environment_type',
            field=models.CharField(choices=[('docker', 'docker'), ('file', '静态文件')], default='docker', max_length=20, verbose_name='环境类型'),
        ),
    ]
