# Generated by Django 3.2.16 on 2022-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20221124_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='environment_type',
            field=models.CharField(choices=[('docker', 'docker'), ('file', '静态文件')], default='docker', max_length=20, verbose_name='环境类型'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='flag'),
        ),
    ]
