# Generated by Django 3.2.16 on 2023-01-19 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20230119_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='难度'),
        ),
    ]
