# Generated by Django 3.2.16 on 2023-01-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challenge_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='describe',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
    ]
