# Generated by Django 3.2.16 on 2022-11-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challengedockerconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='附件名')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='challenge_file/', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '题目附件',
                'verbose_name_plural': '题目附件',
                'db_table': 'challenge_attachment',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='have_attachment',
            field=models.BooleanField(default=False, verbose_name='是否有附件'),
        ),
        migrations.AddField(
            model_name='challengedockerconfig',
            name='challenge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docker_config', to='challenge.challenge', verbose_name='题目'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChallengeFile',
        ),
        migrations.AddField(
            model_name='challengeattachment',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='challenge.challenge', verbose_name='题目'),
        ),
    ]
