# Generated by Django 3.2.16 on 2022-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20221124_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeattachment',
            name='title',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='environment_type',
            field=models.CharField(choices=[('docker', 'docker'), ('file', '静态文件')], default='docker', max_length=20, verbose_name='类型'),
        ),
    ]
