# Generated by Django 3.2.16 on 2022-11-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20221124_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签列表',
                'verbose_name_plural': '标签列表',
                'db_table': 'challenge_Tag_list',
            },
        ),
        migrations.RenameModel(
            old_name='ChallengeAttachment',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='ChallengeDockerConfig',
            new_name='DockerConfig',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '题目分类', 'verbose_name_plural': '题目分类'},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenge.category', verbose_name='题目分类'),
        ),
        migrations.CreateModel(
            name='ChallengeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.tag')),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
                'db_table': 'challenge_Tag',
            },
        ),
    ]
