# Generated by Django 3.2.16 on 2022-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challenge_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tag',
            field=models.ManyToManyField(to='challenge.Tag', verbose_name='标签'),
        ),
    ]
