# Generated by Django 3.2.16 on 2022-11-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20221125_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagList',
        ),
    ]
