# Generated by Django 3.2.16 on 2022-11-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20221124_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='describe',
            field=models.CharField(blank=True, default='这是题目描述', max_length=128, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='have_attachment',
            field=models.BooleanField(verbose_name='是否有附件'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_fixed_flag',
            field=models.BooleanField(verbose_name='flag是否固定'),
        ),
    ]
