# Generated by Django 3.2.16 on 2022-11-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_rename_tag_taglist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taglist',
            table='challenge_tag_list',
        ),
    ]
