# Generated by Django 3.2.16 on 2022-11-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_taglist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challengetag',
            table='challenge_tag',
        ),
    ]
