# Generated by Django 3.2.16 on 2022-11-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20221124_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeattachment',
            name='file_path',
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Pwn', 'Pwn'), ('Reverse', 'Reverse'), ('Crypto', 'Crypto'), ('Misc', 'Misc'), ('Other', 'Other')], default='Web', max_length=64, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='challengeattachment',
            name='file',
            field=models.FileField(default=1, help_text='若设置有题目附件请填写此项', upload_to='challenge_file/', verbose_name='文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='have_attachment',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='是否有题目附件'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_fixed_flag',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='flag是否固定'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='state',
            field=models.BooleanField(choices=[(True, '开放'), (False, '隐藏')], default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=128, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='challengedockerconfig',
            name='challenge_two',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_config', to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='challengedockerconfig',
            name='memory_limit',
            field=models.PositiveSmallIntegerField(default=128, help_text='单位为M', verbose_name='内存限制'),
        ),
        migrations.AlterField(
            model_name='challengedockerconfig',
            name='name',
            field=models.CharField(help_text='若设置题目类型为docker请填写此项', max_length=256, verbose_name='镜像名'),
        ),
    ]
