# Generated by Django 3.2.16 on 2022-11-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challenge_tag'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFinishedChallenge',
            new_name='FinishedChallenge',
        ),
        migrations.AlterModelOptions(
            name='finishedchallenge',
            options={'verbose_name': '完成的题目记录', 'verbose_name_plural': '完成的题目记录'},
        ),
        migrations.AlterModelTable(
            name='finishedchallenge',
            table='finished_challenge',
        ),
    ]
