# Generated by Django 3.2.16 on 2022-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_challenge_tag'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_challenge',
            field=models.ManyToManyField(to='challenge.Challenge', verbose_name='完成的题目'),
        ),
    ]
