# Generated by Django 3.2.16 on 2022-11-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challenge_tag'),
        ('user', '0002_auto_20221125_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(choices=[(True, '成功'), (False, '失败')], default=False, verbose_name='解题状态')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_info', to='challenge.challenge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '解题记录',
                'verbose_name_plural': '解题记录',
                'db_table': 'solve_info',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finished_challenge',
        ),
        migrations.DeleteModel(
            name='FinishedChallenge',
        ),
        migrations.AddField(
            model_name='solveinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Solve_Info',
            field=models.ManyToManyField(through='user.SolveInfo', to='challenge.Challenge', verbose_name='解题记录'),
        ),
    ]
