# Generated by Django 3.2.16 on 2022-11-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_challenge_tag'),
        ('user', '0002_profile_finished_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinishedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='finished_challenge',
            field=models.ManyToManyField(through='user.UserFinishedChallenge', to='challenge.Challenge', verbose_name='完成的题目'),
        ),
    ]
